# Generated by Django 5.0 on 2024-01-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackpot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackpot',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
